# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\Qt\Tools\CMake_64\bin\cmake.exe

# The command to remove a file.
RM = D:\Qt\Tools\CMake_64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "D:\3D\New folder\pyprojects\PhoneDiagnosticApp c++"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "D:\3D\New folder\pyprojects\PhoneDiagnosticApp c++\build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	D:\Qt\Tools\CMake_64\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	D:\Qt\Tools\CMake_64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\3D\New folder\pyprojects\PhoneDiagnosticApp c++\build\CMakeFiles" "D:\3D\New folder\pyprojects\PhoneDiagnosticApp c++\build\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\3D\New folder\pyprojects\PhoneDiagnosticApp c++\build\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PhoneDiagnosticApp

# Build rule for target.
PhoneDiagnosticApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 PhoneDiagnosticApp
.PHONY : PhoneDiagnosticApp

# fast build rule for target.
PhoneDiagnosticApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/build
.PHONY : PhoneDiagnosticApp/fast

#=============================================================================
# Target rules for targets named PhoneDiagnosticApp_autogen_timestamp_deps

# Build rule for target.
PhoneDiagnosticApp_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 PhoneDiagnosticApp_autogen_timestamp_deps
.PHONY : PhoneDiagnosticApp_autogen_timestamp_deps

# fast build rule for target.
PhoneDiagnosticApp_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp_autogen_timestamp_deps.dir\build.make CMakeFiles/PhoneDiagnosticApp_autogen_timestamp_deps.dir/build
.PHONY : PhoneDiagnosticApp_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named PhoneDiagnosticApp_autogen

# Build rule for target.
PhoneDiagnosticApp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 PhoneDiagnosticApp_autogen
.PHONY : PhoneDiagnosticApp_autogen

# fast build rule for target.
PhoneDiagnosticApp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp_autogen.dir\build.make CMakeFiles/PhoneDiagnosticApp_autogen.dir/build
.PHONY : PhoneDiagnosticApp_autogen/fast

PhoneDiagnosticApp_autogen/mocs_compilation.obj: PhoneDiagnosticApp_autogen/mocs_compilation.cpp.obj
.PHONY : PhoneDiagnosticApp_autogen/mocs_compilation.obj

# target to build an object file
PhoneDiagnosticApp_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/PhoneDiagnosticApp_autogen/mocs_compilation.cpp.obj
.PHONY : PhoneDiagnosticApp_autogen/mocs_compilation.cpp.obj

PhoneDiagnosticApp_autogen/mocs_compilation.i: PhoneDiagnosticApp_autogen/mocs_compilation.cpp.i
.PHONY : PhoneDiagnosticApp_autogen/mocs_compilation.i

# target to preprocess a source file
PhoneDiagnosticApp_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/PhoneDiagnosticApp_autogen/mocs_compilation.cpp.i
.PHONY : PhoneDiagnosticApp_autogen/mocs_compilation.cpp.i

PhoneDiagnosticApp_autogen/mocs_compilation.s: PhoneDiagnosticApp_autogen/mocs_compilation.cpp.s
.PHONY : PhoneDiagnosticApp_autogen/mocs_compilation.s

# target to generate assembly for a file
PhoneDiagnosticApp_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/PhoneDiagnosticApp_autogen/mocs_compilation.cpp.s
.PHONY : PhoneDiagnosticApp_autogen/mocs_compilation.cpp.s

src/ADBManager.obj: src/ADBManager.cpp.obj
.PHONY : src/ADBManager.obj

# target to build an object file
src/ADBManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/ADBManager.cpp.obj
.PHONY : src/ADBManager.cpp.obj

src/ADBManager.i: src/ADBManager.cpp.i
.PHONY : src/ADBManager.i

# target to preprocess a source file
src/ADBManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/ADBManager.cpp.i
.PHONY : src/ADBManager.cpp.i

src/ADBManager.s: src/ADBManager.cpp.s
.PHONY : src/ADBManager.s

# target to generate assembly for a file
src/ADBManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/ADBManager.cpp.s
.PHONY : src/ADBManager.cpp.s

src/ComponentTester.obj: src/ComponentTester.cpp.obj
.PHONY : src/ComponentTester.obj

# target to build an object file
src/ComponentTester.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/ComponentTester.cpp.obj
.PHONY : src/ComponentTester.cpp.obj

src/ComponentTester.i: src/ComponentTester.cpp.i
.PHONY : src/ComponentTester.i

# target to preprocess a source file
src/ComponentTester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/ComponentTester.cpp.i
.PHONY : src/ComponentTester.cpp.i

src/ComponentTester.s: src/ComponentTester.cpp.s
.PHONY : src/ComponentTester.s

# target to generate assembly for a file
src/ComponentTester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/ComponentTester.cpp.s
.PHONY : src/ComponentTester.cpp.s

src/HardwareScanner.obj: src/HardwareScanner.cpp.obj
.PHONY : src/HardwareScanner.obj

# target to build an object file
src/HardwareScanner.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/HardwareScanner.cpp.obj
.PHONY : src/HardwareScanner.cpp.obj

src/HardwareScanner.i: src/HardwareScanner.cpp.i
.PHONY : src/HardwareScanner.i

# target to preprocess a source file
src/HardwareScanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/HardwareScanner.cpp.i
.PHONY : src/HardwareScanner.cpp.i

src/HardwareScanner.s: src/HardwareScanner.cpp.s
.PHONY : src/HardwareScanner.s

# target to generate assembly for a file
src/HardwareScanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/HardwareScanner.cpp.s
.PHONY : src/HardwareScanner.cpp.s

src/MainWindow.obj: src/MainWindow.cpp.obj
.PHONY : src/MainWindow.obj

# target to build an object file
src/MainWindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/MainWindow.cpp.obj
.PHONY : src/MainWindow.cpp.obj

src/MainWindow.i: src/MainWindow.cpp.i
.PHONY : src/MainWindow.i

# target to preprocess a source file
src/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/MainWindow.cpp.i
.PHONY : src/MainWindow.cpp.i

src/MainWindow.s: src/MainWindow.cpp.s
.PHONY : src/MainWindow.s

# target to generate assembly for a file
src/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/MainWindow.cpp.s
.PHONY : src/MainWindow.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\PhoneDiagnosticApp.dir\build.make CMakeFiles/PhoneDiagnosticApp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... PhoneDiagnosticApp_autogen
	@echo ... PhoneDiagnosticApp_autogen_timestamp_deps
	@echo ... PhoneDiagnosticApp
	@echo ... PhoneDiagnosticApp_autogen/mocs_compilation.obj
	@echo ... PhoneDiagnosticApp_autogen/mocs_compilation.i
	@echo ... PhoneDiagnosticApp_autogen/mocs_compilation.s
	@echo ... src/ADBManager.obj
	@echo ... src/ADBManager.i
	@echo ... src/ADBManager.s
	@echo ... src/ComponentTester.obj
	@echo ... src/ComponentTester.i
	@echo ... src/ComponentTester.s
	@echo ... src/HardwareScanner.obj
	@echo ... src/HardwareScanner.i
	@echo ... src/HardwareScanner.s
	@echo ... src/MainWindow.obj
	@echo ... src/MainWindow.i
	@echo ... src/MainWindow.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

